"""Initial schema

Revision ID: 6568d4b91f72
Revises:
Create Date: 2025-09-02 10:54:56.266210

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6568d4b91f72"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.alter_column("content", existing_type=sa.TEXT(), nullable=False)

    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.alter_column("owner_id", existing_type=sa.INTEGER(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.alter_column("owner_id", existing_type=sa.INTEGER(), nullable=True)

    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.alter_column("content", existing_type=sa.TEXT(), nullable=True)

    # ### end Alembic commands ###
