"""Initial migration with Product models

Revision ID: 30c640606e46
Revises:
Create Date: 2025-08-19 11:19:13.285583

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "30c640606e46"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.add_column(sa.Column("id", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("name", sa.String(length=100), nullable=False))
        batch_op.alter_column(
            "type", existing_type=sa.VARCHAR(length=50), nullable=False
        )
        batch_op.alter_column("expiry_date", existing_type=sa.DATE(), nullable=False)
        batch_op.alter_column(
            "warranty_period", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.alter_column(
            "author",
            existing_type=sa.VARCHAR(length=255),
            type_=sa.String(length=100),
            nullable=False,
        )
        batch_op.alter_column("pages", existing_type=sa.INTEGER(), nullable=False)
        batch_op.drop_column("product_id")
        batch_op.drop_column("product_name")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "product_name",
                sa.VARCHAR(length=255),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column("product_id", sa.INTEGER(), autoincrement=True, nullable=False)
        )
        batch_op.alter_column("pages", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column(
            "author",
            existing_type=sa.String(length=100),
            type_=sa.VARCHAR(length=255),
            nullable=True,
        )
        batch_op.alter_column(
            "warranty_period", existing_type=sa.INTEGER(), nullable=True
        )
        batch_op.alter_column("expiry_date", existing_type=sa.DATE(), nullable=True)
        batch_op.alter_column(
            "type", existing_type=sa.VARCHAR(length=50), nullable=True
        )
        batch_op.drop_column("name")
        batch_op.drop_column("id")

    # ### end Alembic commands ###
