"""Initial products schema

Revision ID: fe37d633494d
Revises: 3376776143ff
Create Date: 2025-08-21 16:15:36.845907

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fe37d633494d"
down_revision = "3376776143ff"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("product_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column("warranty_period", sa.Integer(), nullable=True),
        sa.Column("author", sa.String(length=100), nullable=True),
        sa.Column("pages", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("product_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("products")
    # ### end Alembic commands ###
