"""Add users table for authentication and RBAC

Revision ID: 09e47cfc8472
Revises: fe37d633494d
Create Date: 2025-08-25 12:42:13.335093

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "09e47cfc8472"
down_revision = "fe37d633494d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=80), nullable=False),
        sa.Column("password_hash", sa.String(length=200), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
